name: drmem_provider
description: A DrMem control system widget
version: 0.1.0
homepage: https://github.com/DrMemCS
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  nsd: ^4.0.0

  dart_drmem:
    git:
      url: git@github.com:rneswold/dart-drmem.git
      ref: pull-request

#  built_value: ^8.9.0
#  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: